# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import notas_pb2 as notas__pb2


class GerenciadorNotasStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.inserirNovaMatricula = channel.unary_unary(
                '/GerenciadorNotas/inserirNovaMatricula',
                request_serializer=notas__pb2.Matricula.SerializeToString,
                response_deserializer=notas__pb2.RetornoDefault.FromString,
                )
        self.alterarNotasMatricula = channel.unary_unary(
                '/GerenciadorNotas/alterarNotasMatricula',
                request_serializer=notas__pb2.Matricula.SerializeToString,
                response_deserializer=notas__pb2.RetornoDefault.FromString,
                )
        self.alterarFaltasMatricula = channel.unary_unary(
                '/GerenciadorNotas/alterarFaltasMatricula',
                request_serializer=notas__pb2.Matricula.SerializeToString,
                response_deserializer=notas__pb2.RetornoDefault.FromString,
                )
        self.listaAlunosDisciplina = channel.unary_unary(
                '/GerenciadorNotas/listaAlunosDisciplina',
                request_serializer=notas__pb2.RequestLista.SerializeToString,
                response_deserializer=notas__pb2.ReturnListaAlunos.FromString,
                )
        self.listaDisciplinaAluno = channel.unary_unary(
                '/GerenciadorNotas/listaDisciplinaAluno',
                request_serializer=notas__pb2.RequestLista.SerializeToString,
                response_deserializer=notas__pb2.ReturnListaMatriculas.FromString,
                )


class GerenciadorNotasServicer(object):
    """Missing associated documentation comment in .proto file."""

    def inserirNovaMatricula(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def alterarNotasMatricula(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def alterarFaltasMatricula(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listaAlunosDisciplina(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listaDisciplinaAluno(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GerenciadorNotasServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'inserirNovaMatricula': grpc.unary_unary_rpc_method_handler(
                    servicer.inserirNovaMatricula,
                    request_deserializer=notas__pb2.Matricula.FromString,
                    response_serializer=notas__pb2.RetornoDefault.SerializeToString,
            ),
            'alterarNotasMatricula': grpc.unary_unary_rpc_method_handler(
                    servicer.alterarNotasMatricula,
                    request_deserializer=notas__pb2.Matricula.FromString,
                    response_serializer=notas__pb2.RetornoDefault.SerializeToString,
            ),
            'alterarFaltasMatricula': grpc.unary_unary_rpc_method_handler(
                    servicer.alterarFaltasMatricula,
                    request_deserializer=notas__pb2.Matricula.FromString,
                    response_serializer=notas__pb2.RetornoDefault.SerializeToString,
            ),
            'listaAlunosDisciplina': grpc.unary_unary_rpc_method_handler(
                    servicer.listaAlunosDisciplina,
                    request_deserializer=notas__pb2.RequestLista.FromString,
                    response_serializer=notas__pb2.ReturnListaAlunos.SerializeToString,
            ),
            'listaDisciplinaAluno': grpc.unary_unary_rpc_method_handler(
                    servicer.listaDisciplinaAluno,
                    request_deserializer=notas__pb2.RequestLista.FromString,
                    response_serializer=notas__pb2.ReturnListaMatriculas.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GerenciadorNotas', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GerenciadorNotas(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def inserirNovaMatricula(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GerenciadorNotas/inserirNovaMatricula',
            notas__pb2.Matricula.SerializeToString,
            notas__pb2.RetornoDefault.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def alterarNotasMatricula(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GerenciadorNotas/alterarNotasMatricula',
            notas__pb2.Matricula.SerializeToString,
            notas__pb2.RetornoDefault.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def alterarFaltasMatricula(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GerenciadorNotas/alterarFaltasMatricula',
            notas__pb2.Matricula.SerializeToString,
            notas__pb2.RetornoDefault.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listaAlunosDisciplina(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GerenciadorNotas/listaAlunosDisciplina',
            notas__pb2.RequestLista.SerializeToString,
            notas__pb2.ReturnListaAlunos.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listaDisciplinaAluno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GerenciadorNotas/listaDisciplinaAluno',
            notas__pb2.RequestLista.SerializeToString,
            notas__pb2.ReturnListaMatriculas.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
